{{--

    * Created by   :  Muhammad Yasir
    * Project Name : demedat
    * Product Name : PhpStorm
    * Date         : 10-Nov-16 6:33 PM
    * File Name    : 

--}}
@extends('layouts.default')

<!-- Sidebar right menue -->
@section('content')
    @if(Auth::check())
        @include('includes.sidebar-right-menu')
    @endif
    <div class="bidders-view autoheight">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="h2b mt40">Privacy Policy</div>
                        </div><!-- /.col-sm-8 -->
                    </div>
                    <div class="row">
                        <div class="list-group ">
                            Deliverysure Privacy Policy
                            Deliverysure,  (“Deliverysure”, “we”, or “us”) knows that you care about how your personal information is used and shared, and we take your privacy seriously. Please read the following to learn more about our privacy policy.
                            By visiting or using the Deliverysure website or mobile application, Deliverysure’s services and applications (mobile or otherwise), and any linked pages, features, or content offered from time to time by Deliverysure in connection therewith (collectively, the “Service”), you acknowledge that you accept the practices and policies outlined in this privacy policy.
                            If you do not agree to these terms, please do not use the Service.
                            New York Privacy Rights:
                            New York Civil Code Section § 1798.83 permits New York residents that are users of our Site to request certain information regarding our disclosure of personal information to third parties for their direct marketing purposes. To make such a request, please send an email to support@deliverysure.cim
                            What does this privacy policy cover?
                            This privacy policy describes how personal information is collected, used and disclosed when you use our Service. Please read this notice very carefully.
                            This privacy policy does not apply to the practices of companies that Deliverysure does not own or control, or employees that Deliverysure does not manage. Any information you provide to, or that is collected by a third-party may be subject to the privacy policies of those third parties, if any. We encourage you to read such privacy policies of any third-party websites you visit. It is the sole responsibility of such third parties to adhere to any applicable restrictions on the disclosure of your personally identifying information, and Deliverysure shall not be liable for wrongful use or disclosure of your personally identifying information by any third party. We encourage you to carefully review the privacy policies of any web sites you visit.
                            Children’s Online Privacy Protection Act Compliance:
                            By using Deliverysure, you represent that you are at least 13 years old or older and consent to the privacy practices described in this privacy policy, as may be modified by us from time to time.
                            Deliverysure is not intended for use by children under 13. If you believe that a child has provided Deliverysure with personally identifying information without the consent of his or her parent or guardian, please contact us at support@deliverysure.com. If Deliverysure becomes aware that a child under age 13 has provided us with personally identifying information, we will delete such information.
                            What personally identifying information does Deliverysure collect?
                            As used herein, the term “personally identifying information” means information that specifically identifies an individual (such as a name, address, telephone number, mobile number, e-mail address, or other account name or number), and information about that individual’s location or activities, when directly linked to personally identifying information. Personally identifying information also includes demographic information such as date of birth, gender, geographic area and preferences when such information is linked to other personal information that identifies you.  We may also combine the information we collect from you with information about you that we receive from other online and offline sources in order to provide you with a better experience and to improve the quality of the Service.
                            When you register with Deliverysure we ask you to provide certain personal information, such as a valid email address, location and username. We may collect additional information such as physical address or a mobile phone number and additional authentication information, to provide you with the services you need (such as payment or withdrawal of funds, sending physical goods), or to ensure the marketplace integrity (for example, prevention of fraud). We collect information to provide better services and enhanced user experience to all of our users.
                            In addition, we collect information while you access, browse, and view or otherwise use the Deliverysure website or mobile application. In other words, when you access Deliverysure we are aware of your usage of Deliverysure, and may gather, collect and record the information relating to such usage, including geo-location information, IP address, device and connection information, browser information and web-log information, and all communications recorded by users through Deliverysure. We use that information to enhance user experience, personalize your browsing experience as well as monitor Deliverysure for fraud and inappropriate content or behavior. We may also collect supplemental information obtained from parties such as demographic and navigation data.
                            Personally identifying information does not include “aggregate” information, which is data we collect about the use of Deliverysure or about a group or category of products, services or users, from which individual identities or other personally identifying information has been removed. In other words, information about how you use a service may be collected and combined with information about how others use the same service. Aggregate data helps us understand trends and our users’ needs so that we can better consider new features or otherwise tailor our Service. This privacy policy in no way restricts or limits our collection and use of aggregate information.
                            To preserve the integrity of our databases, we may retain information submitted by users for an indefinite length of time. If required by law, we will delete personally identifying Information by erasing it from our database.
                            How will Deliverysure use the personally identifying information it receives?
                            Deliverysure uses personal information for the following general purposes: (1) to provide our products and the Service, (2) for billing, identification and authentication, and fraud prevention, (3) to analyze usage of the Service and improve our products and the Services, (4) to contact you and deliver administrative notices and communications relevant to your use of our products and the Service, (5) for internal market research, troubleshooting problems, and detecting and protecting against error, fraud or other criminal activity, (6) for distribution to third-party contractors that provide services to Deliverysure and partners of Deliverysure who are bound by privacy restrictions at least as restrictive as those set forth in this privacy policy, (7) to enforce our Terms of Use, and (8) as otherwise set forth in this privacy policy.
                            Although we ensure that our third party agents receiving your information are bound by privacy restrictions at least as restrictive as those set forth in this policy, Deliverysure is not responsible for any issues that may arise regarding the privacy policies of any of its agents, affiliates or advertisers. By using our Service, you do hereby agree to hold Deliverysure harmless from any claims and/or damages that may arise from the actions of any of its agents, affiliates and/or advertisers.
                            Two goals drive Deliverysure’s decisions regarding the use of information collected from users: (1) improving user experience by offering personalized services, content and advertising, and (2) market research.
                            You understand that when you use Deliverysure, it may be possible to post certain information to third party sites such as Facebook® or Twitter® through the mobile app.  This data may be shared with other users and posted in publicly available portions of these third party sites.  Deliverysure has no control of your data once you choose to post it, and you should be aware that location data and other information that you post may be publicly available and can potentially be viewed by anyone.
                            Aggregate information and location data may be shared with carriers, service providers and other third parties in accordance with the provisions of this privacy policy. If the location data is shared with carriers, service providers and other third parties then it will be done so in a way to keep your anonymity. Location data will not be shared in such a way as to be personally identifying.
                            In some cases we may choose to buy or sell assets. In these types of transactions, user information is typically one of the business assets that is transferred. Moreover, if Deliverysure or substantially all of its assets were acquired, or in the unlikely event that Deliverysure goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Deliverysure may continue to use your personally identifying and non-personally identifying information only as set forth in this privacy policy. Otherwise, Deliverysure will never rent or sell potentially personally identifying information to anyone.
                            Other than to its employees, agents, contractors and affiliated organizations or as described above, Deliverysure discloses potentially personally identifying and personally identifying information only when required to do so by law, or when Deliverysure believes in good faith that disclosure is reasonably necessary to protect the property or rights of Deliverysure, third parties or the public at large.
                            If you are a registered user of Deliverysure and have supplied your email address, Deliverysure may occasionally send you an email to tell you about new features, solicit your feedback, introduce events, other companies or products that we think might interest you or just keep you up to date with what’s going on with Deliverysure and our products.
                            Is personally identifying information about me secure?
                            Your Deliverysure account personal information is protected by a password for your privacy and security. You need to prevent unauthorized access to your account and personal information by selecting and protecting your password appropriately and limiting access to your computer and browser by signing off after you have finished accessing your account.  In addition, we recommend you enable a pass code key on your mobile device.
                            If someone who represents to you they are Deliverysure staff and asks for any personal account information, including password, check their URL. If it doesn’t say they are support@deliverysure.com then they aren’t.
                            Deliverysure has implemented commercially reasonable technical and organizational measures designed to implement your privacy settings and secure your personal information from accidental loss and from unauthorized access, use, alteration or disclosure. However, we cannot guarantee that unauthorized third parties will never be able to defeat those measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.
                            What about cookies?
                            Cookies are alphanumeric identifiers that we transfer to your computer’s hard drive through your browser to enable our systems to recognize your browser and tell us how and when pages of the Service are visited and by how many people. Deliverysure cookies do not collect personal information, and we do not combine the general information collected through cookies with other personal information to tell us who you are or what your screen name or email address is.
                            Most browsers have an option for turning off the cookie feature, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allowing you to decide on acceptance of each new cookie in a variety of ways.
                            Ads that may appear on the Service may be delivered to users by our advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy covers the use of cookies by Deliverysure and does not cover the use of cookies by any advertisers.
                            If you do not accept cookies, however, you will not be able to use all portions or all functionalities of the Service. We and our service providers may also use “pixel tags,” “web beacons,” “clear GIFs,” or similar means in connection with the Service and HTML-formatted email messages to, among other things, track the actions of users and email recipients, to determine the success of marketing campaigns and to compile aggregate statistics about our Service usage and response rates. We may also engage one or more third party service providers to serve online advertisements on our behalf. They also may use a “pixel tag” to collect anonymous information about visits to our Service and to other websites, and they may use that information to target advertisements for goods and services. This information is collected anonymously, in a manner that does not personally identify you.
                            What about other services offered by Deliverysure?
                            In the event we make chat, messaging, message boards and/or Messaging Services available to you (collectively, “Messaging Services”), you will be solely responsible for the information and any other content you post on and through these Messaging Services and should be aware that when you voluntarily disclose personally identifying information (e.g., name, e-mail address, telephone number) on or through these Messaging Services, such information is generally accessible to, and may be collected and used by, other users. This may result in unsolicited messages from third parties, and such messages are beyond our control. We do not exercise control over any users or visitors, and in no way are we responsible, nor do we have any liability whatsoever, for any collection or use of information you may disclose through the Messaging Services. This privacy policy does not cover such disclosure of information. You are encouraged to exercise discretion when providing personally identifying information about yourself in and through Messaging Services. Please do not post any personally identifying information on the Messaging Services that you expect to keep private.
                            Changes to this privacy policy
                            Deliverysure reserves the right to change our privacy policy from time to time. If we do then we’ll notify you by posting the amended policy on www.deliverysure.com. In all cases, use of information we collect now is subject to the privacy policy in effect at the time such information is used.  Your use of Deliverysure following the posting of such changes or revised statement shall constitute your consent to any changes in our privacy practices, and you expressly waive any right to notice of such changes. We encourage you to review this privacy policy whenever you visit www.deliverysure.com to make sure that you understand how any information you provide will be used.
                            Questions or concerns
                            If you have any questions or concerns regarding privacy using the Service, please send us a detailed message to: support@deliverysure.com. We will make every effort to resolve your concerns.


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
