{{--

    * Created by   :  Muhammad Yasir
    * Project Name : demedat
    * Product Name : PhpStorm
    * Date         : 10-Nov-16 6:33 PM
    * File Name    :

--}}
@extends('layouts.default')

<!-- Sidebar right menue -->
@section('content')
    @if(Auth::check())
        @include('includes.sidebar-right-menu')
    @endif
    <div class="bidders-view autoheight">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="h2b mt40">Terms of use</div>
                        </div><!-- /.col-sm-8 -->
                    </div>
                    <div class="row">
                        <div class="list-group ">
                            <p><b>PLEASE READ THESE TERMS OF SERVICE (THESE “Terms of Service”) CAREFULLY BEFORE USING THE INTERNET WEBSITE LOCATED AT [DeliverySure.COM], ANY OF ITS SUBDOMAINS or any software applications included or accessible through such website(s) (COLLECTIVELY, THE “DeliverySure Applications” on apple store, Andriod store and any other mobile and online stores).</b><br></p>
                           <p> (“DeliverySure” or “we”).  All references to “User” in these Terms of Service shall refer to you as well as other users of the DeliverySure Applications and the Service (as defined below), and all references to persons shall refer to any natural person, partnership, joint venture, association, corporation, limited liability company, trust, estate or other entity.</p>
                            By using the DeliverySure Applications and/or the Service, you signify your acceptance of and agreement to the terms and conditions set forth in these Terms of Service.  You must be 18 years or older to use the DeliverySure Applications and/or the Service.  If you do not accept and agree to these Terms of Service, or if you are younger than 18 years of age, you must immediately cease your use of the DeliverySure Applications and the Service.
                            We reserve the right to alter these Terms of Service at any time.  If so altered, we will post our updated Terms of Service on this page and post notice of the change so it is visible when you visit and/or log-on to the DeliverySure Applications for the first time after the change is posted.  Your continued use of the DeliverySure Applications after the changes have been posted shall constitute your acceptance of the changes.  If you do not agree to the updated Terms of Service, you must immediately cease your use of the DeliverySure Applications and the Service.
                            1.              Service
                            The “DeliverySure” Applications provide an online service that, among other things, allows Users to connect and communicate for the purpose of ordering and delivering (the “Service”).  Users consist of persons (“Drivers”) offering to deliver products to other Users (“Purchasers”) to certain location(s) as well as persons (“Retailer”) seeking to obtain orders from (“Purchasers”) and have (“Drivers”) to pick up from specified location(s) and deliver to other specified location(s).
                            2.              Access Rights
                            Subject to the terms and conditions set forth in these Terms of Service, DeliverySure hereby grants you a limited, fully revocable, non-exclusive, non-transferable, non-assignable right to access and use the DeliverySure Applications solely for your personal use in connection with accessing and using the Service.  DeliverySure may suspend or terminate your right to access and use the DeliverySure Applications and/or the Service at any time and for any reason.
                            When you sign up to use the Service, you will be required to create a user name and password but you can also use your Facebook.com login information, and you may be asked from time to time to provide additional information to supplement your profile.  You are responsible for the security of all passwords and other access credentials required accessing the DeliverySure Applications or the Service.  You are responsible for any activity that occurs under your Facebook account or other user name involving the DeliverySure Applications or the Service. You agree to notify DeliverySure immediately if you suspect any unauthorized use of your password or access to your account.  You shall not use the account, user name or password of another User at any time, nor shall you permit any other person to use your account, user name or password to access or use the DeliverySure applications and/or the Service.
                            3.              Waiver and Release
                            In consideration of being allowed to access and use the DeliverySure Applications and the Service, and prior to conducting any transactions using the DeliverySure Applications or the Service, you will be required to accept and agree to the Release and Wavier of Liability.  Your acceptance of and agreement to the Release and Waiver of Liability is an essential condition to your right to access and use the Service.
                            4.              Payment Terms
                            [DeliverySure utilizes a third-party provider to process all payments made by Users in connection with any transactions involving the DeliverySure Applications and the Service.  DeliverySure is not a bank or other chartered depository institution.]
                            By providing DeliverySure with your payment information (including any credit card information), you agree that DeliverySure is authorized to immediately charge your account for all fees and charges due and payable to DeliverySure (and any other User) as a result of the transactions conducted using the DeliverySure Applications or the Service. You agree that no additional notice or consent is required before DeliverySure charges such account. You agree to immediately notify DeliverySure of any changes in your account/payment information.  DeliverySure reserves the right, at any time, to change its prices and billing methods, either immediately upon posting notice of the changes on the DeliverySure Applications and/or by e-mail notification to your e-mail address on file in connection with your account.
                            Taxes, fees and other charges (including sales, use or value-added taxes) incurred in connection with a User’s use of the Service (including any such taxes, fees or charges due in connection with payments made to any other User) shall be the responsibility of such User and DeliverySure shall have no responsibility to collect or withhold any amounts from Users for the purpose of paying such taxes, fees or other charges to a government authority.
                            5.              USAGE RESTRICTIONS
                            You may not, nor may you authorize any third party to: (a)modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit the DeliverySure Applications in any manner; (b) use the DeliverySure Applications as a service bureau; (c) rent, lease, loan, sell, license, publish, display, resell for profit, or distribute the DeliverySure Applications or any part of the DeliverySure Applications; (d) remove or alter any proprietary notice or legend regarding DeliverySure’s proprietary rights in the DeliverySure Applications; (e) transmit any worms or viruses or any code of a destructive nature on or through the DeliverySure Applications or introduce software or automated agents to the DeliverySure Applications, generate automated messages, or strip or mine data from the DeliverySure Applications; (f) use the DeliverySure Applications or any information obtained from the DeliverySure Applications in order to contact, advertise to, solicit, or sell to any User without their prior explicit consent; or (i) use the DeliverySure Applications or the Service in any way that: (i) violates any applicable laws and regulations; (ii) accesses or copies any data or information of other Users; (iii) interferes with or disrupts the integrity or performance of the DeliverySure Applications or the information contained therein; (iv) abuses, intimidates, harasses, threatens or interferes with another User’s use of the DeliverySure Applications; (v) interferes with, disrupts or creates an undue burden on the DeliverySure Applications or the networks or services connected to the DeliverySure Applications or (vi) is not permitted by these Terms of Service.
                            6.              OWNERSHIP
                            The DeliverySure Applications, and all worldwide intellectual property rights and proprietary rights related thereto, are the exclusive property of DeliverySure and its licensors. DeliverySure and its licensors reserve all rights in and to DeliverySure Applications not expressly granted to you in this Agreement, and no other licenses or rights are granted by implication, estoppel or otherwise.
                            To the extent that you provide DeliverySure with any suggestions, information, ideas or feedback concerning the DeliverySure Applications and the Service, including through e-mails, voicemails, postings or feedback forms (“Feedback”), any such Feedback will be the sole and exclusive property of DeliverySure.  You agree to assign and hereby assign to DeliverySure all right, title and interest worldwide in and to the Feedback, and all related intellectual property rights, and you agree to assist DeliverySure in perfecting and enforcing such rights.   You agree that any Feedback you submit is not being made in confidence or trust and that no confidential, advisory or fiduciary relationship is intended or created between you and DeliverySure in any way.  You further acknowledge and agree that you have no expectation of any review, compensation or consideration of any of your Feedback.
                            Please be sure that any information you include when using the Service, including in any Feedback, is information that you are comfortable sharing with others.
                            7.              Warranty
                            You represent and warrant to DeliverySure that (a) you have the legal power and authority to agree to and be bound by the terms and conditions set forth in these Terms of Service; (b) you have not falsely identified yourself nor provided any false information to gain access to the DeliverySure Applications; (c) you will comply with all applicable laws and regulations during the course of your use of the DeliverySure Applications and the Service; and (d) if you are a Driver, you will (i) be licensed to operate the motor vehicle used in transporting any order, and (ii) maintain adequate insurance in an amount equal to or in excess of (1) $300,000 combined single limit, or (2) that required by applicable law or regulation, whichever is greater.
                            8.              Disclaimer
                            DeliverySure is not a provider of transportation Services and your participation (whether as a Driver, Purchaser or Retailer) is “at your own risk”. DeliverySure does not control, is not responsible for and makes no representations or warranties with respect to any User or the conduct of any user.  DeliverySure has no involvement, makes no representations or warranties as to, and has no responsibility or liability with respect to any communications, transactions, interactions, disputes or any relations between you and any other User or person.  You are solely responsible for your interaction with or reliance on any User or User conduct.  DeliverySure does not verify whether, or perform any investigation to determine if, drivers are properly licensed to operate the motor vehicle used in transporting any product and/or maintain adequate insurance in an amount equal to or in excess of that required by applicable law or regulation.  DeliverySure does not provide or inspect any motor vehicle used in delivering, transporting, and makes no representations or warranties, and hereby disclaims any representations and warranties, as to the suitability of such motor vehicles for the purposes of providing transportation for the passengers.  You must perform any necessary or appropriate investigation or inquiry with respect to any User or User conduct.
                            THE DeliverySure Applications and the Service are provided as-is and DeliverySure AND ITS LICENSORS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND REPRESENTATIONS OF ANY KIND WITH REGARD TO THE DeliverySure Applications and the Service and your use of the DeliverySure Applications and the Service under these Terms of Service, INCLUDING ANY WARRANTY OF NON-INFRINGEMENT, TITLE, FITNESS FOR A PARTICULAR PURPOSE, FUNCTIONALITY, DATA ACCURACY OR MERCHANTABILITY, WHETHER EXPRESS, IMPLIED OR STATUTORY.  Without limiting the foregoing, DeliverySure DOES NOT WARRANT THAT THE DeliverySure Applications and the Service WILL MEET YOUR REQUIREMENTS, OR THAT THE OPERATION AND RESULTS OF THE DeliverySure Applications WILL BE UNINTERRUPTED, ERROR-FREE or will yield any specific results, OR THAT DEFECTS IN THE DeliverySure Applications WILL BE CORRECTED. YOU ACKNOWLEDGE AND AGREE THAT DeliverySure HAS NO OBLIGATION TO CORRECT ANY DEFECTS OR ERRORS IN THE DeliverySure Applications, REGARDLESS OF WHETHER YOU INFORM DeliverySure OF SUCH DEFECTS OR ERRORS OR DeliverySure OTHERWISE BECOMES AWARE OF, SUCH DEFECTS OR ERRORS. We are not responsible for the accuracy or completeness of information available from or through the DeliverySure Applications or the Service.
                            SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY MAY LAST, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.

                            9.              Limited Remedy; LIMITATION ON LIABILITY
                            Your sole recourse for dissatisfaction with the DeliverySure Applications and/or the Service is to stop using the DeliverySure Applications and the Service.  To the maximum extent permitted by applicable law, DeliverySure shall not be liable for any loss or damage, including personal injury or death, arising out of or resulting from your use of or reliance on the DeliverySure Applications and/or the Service, including your participation (whether as a driver, Purchaser or a Retailer) or any transactions, interactions, communications, disputes or relations between Users or any other person, whether online or offline. THIS LIMITATION OF LIABILITY IS INTENDED TO APPLY WITHOUT REGARD TO WHETHER OTHER PROVISIONS OF THIS AGREEMENT HAVE BEEN BREACHED OR HAVE PROVEN INEFFECTIVE, and without regard to the types of damages claimed, including any direct, indirect, incidental, special, consequential or punitive damages, whether under any contract, negligence, strict liability or other theory, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.   THIS limited remedy GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS, WHICH VARY FROM JURISDICTION TO JURISDICTION.

                            10.            Indemnification
                            You shall defend, indemnify, and hold DeliverySure, its subsidiaries and affiliates, and each of their officers, employees agents, and other partners harmless from any loss, liability, claim, or demand (including reasonable attorney’s fees) arising from any third-party claim due to or arising out of your (a) use, or any use by a person using your account, of the DeliverySure Applications and/or the Service in violation of, or in a manner not authorized by, these Terms of Service; (b) participation (whether as a Driver, Purchaser or a Retailer); or (c) negligence or willful misconduct.

                            11.           Trademarks
                            The trademarks, logos and service marks (“Marks”) displayed with the DeliverySure Applications or the Service are the property of DeliverySure or its licensors. You are not permitted to use these Marks without the prior written consent of the third party that owns such Marks.

                            12.           Electronic communications
                            The communications between you and DeliverySure use electronic means, whether you visit the DeliverySure Applications or send DeliverySure e-mails, or whether DeliverySure posts notices on the DeliverySure Applications or communicates with you via e-mail. You hereby (a) consent to receive communications from DeliverySure in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that DeliverySure provides to you electronically satisfy any legal requirement that such communications would satisfy if it were be in writing.  The foregoing does not affect your statutory rights.
                            13.           U.S. Export Controls
                            The content and software available in connection with the DeliverySure Applications and the Service are further subject to United States export controls, and no such content or software may be downloaded from the DeliverySure Applications and the Service or otherwise exported or re-exported in violation of applicable United States export laws and/or regulations.
                            14.           Governing Law and Injunctive Relief
                            The laws of the State of New York shall govern these Terms of Service without giving effect to any conflict of laws principles that may provide the application of the law of another jurisdiction.  You and DeliverySure agree to submit to the jurisdiction of, and agree that venue is proper in, the state courts located in EDNY; Eastern District of New York, NY (USA) and the federal courts located in the Eastern District of New York, NY (USA) in such legal action or proceeding. The application of the United Nations Convention on the International Sale of Goods is hereby expressly excluded. DeliverySure may seek injunctive or other equitable relief to protect its intellectual property rights in any court of competent jurisdiction.  You shall always comply with all the international and domestic laws, ordinance, regulations and statutes that are applicable to your use of the Service and your participation in (whether as a Driver, Purchaser or a Retailer).

                            15.           Links to Third Party Websites
                            The DeliverySure Applications may be linked to other websites that are not DeliverySure websites (“Third Party Websites”) and certain areas of the DeliverySure Applications may allow you to conduct transactions or purchase goods or services from or through such Third Party Websites. DeliverySure is providing these links to you as a convenience, and DeliverySure does not verify, make any representations or take any responsibility for such linked to Third Party Websites, including the truthfulness, accuracy, quality or completeness of the content, links displayed or activities conducted on such Third Party Websites.  The Third Party Websites may have different privacy policies and terms and conditions and business practices than those of DeliverySure.  Your dealings and communications through the DeliverySure Applications with any person other than DeliverySure are solely between you and such person.   Any complaints, concerns or questions you have relating to materials provided by third parties should be forwarded directly to the applicable third party.  Any reference on the DeliverySure Applications to any product, process, publication or service of any third party, by trade name, domain name, trademark, trade identity, service mark, logo, manufacturer or otherwise does not constitute or imply the endorsement or recommendation of DeliverySure.

                            16.           General
                            DeliverySure may assign these Terms of Service, in whole or in part, at any time. You may not assign these Terms of Service, or any part thereof, to any other person.  Any attempt by you to do so is null and void.  If any provision of these Terms of Service is held to be unenforceable, that provision will be enforced to the extent permissible by law and the remaining provisions will remain in full force.  No waiver under these Terms of Service will be valid or binding unless set forth in writing and duly executed by the party against whom enforcement of such waiver is sought.  Any such waiver will constitute a waiver only with respect to the specific matter described therein and will in no way impair the rights of the party granting such waiver in any other respect or at any other time.  Any delay or forbearance by either party in exercising any right hereunder will not be deemed a waiver of that right. When used in these Terms of Service, “including” and words of similar import mean “including but not limited to”.  Any claim related to the DeliverySure Applications or the Service must be brought within one year from the date on which the claim first could be filed, or such claim will be permanently barred.  The proprietary rights, disclaimer of warranties, indemnities, limitations of liability and definitions and rights, duties and obligations of the parties that by their nature continue and survive shall survive any termination of these Terms of Service.
                            If you have any questions regarding these Terms of Service, the DeliverySure Applications or the Service, please direct all correspondence to: [contact@ DeliverySure.com].
                            17.           [Copyright Infringement
                            DeliverySure will review all claims of copyright infringement submitted by the applicable copyright owner or the copyright owner’s legal agent.
                            To make a claim, please provide DeliverySure with the following:
                            1.            a description of the infringing material and information reasonably sufficient to permit DeliverySure to locate the material, as well as a description of the copyrighted work claimed to have been infringed.
                            2.             a statement by you that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or applicable law;
                            3.            a physical or electronic signature of the copyright owner or the person authorized to act on its behalf and your contact information, including your address, telephone number and e-mail address; and
                            4.            a statement that the information in the notification is accurate, and under the pains and penalties of perjury, that you are authorized to act on behalf of the copyright owner.
                            Contact information for the DeliverySure Copyright Agent for notice of claims of copyright infringement is as follows: 9 Hinton Ave, Babylon, NY 11702

                            YOU HEREBY ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THESE TERMS OF USE AND PRIVACY POLICY, AND AGREE THAT YOUR USE OF THE PLATFORM IS AN ACKNOWLEDGMENT OF YOUR AGREEMENT TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
                            If you don’t agree to the Terms contained in this agreement, please exit the Platform.
                            Deliverysure © Copyright 2016

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
